### ISSUE TITLE
Confused about the repo name 'prow-tutorial'

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/prow-tutorial#21]
This repo is not only a tutorial. Actually, the role of this repo is much more like an infra. I'd suggest that we rename this repo. For example: `kubesphere-infra`. Of course, the tutorial part can still be inside.

**Comment by FeynmanZhou** [comment]
> This repo is not only a tutorial. Actually, the role of this repo is much more like an infra. I'd suggest that we rename this repo. For example: `kubesphere-infra`. Of course, the tutorial part can still be inside.

Agree, it should be renamed with `infra`, I assume this repo includes the configuration of Prow Robot in the KubeSphere organization? BTW, the Readme should be rewritten in English.
